title: Jayden Lee
logo: /assets/img/profile.jpg
show_downloads: false
theme: jekyll-theme-minimal
social_links:
  linkedin: https://www.linkedin.com/in/jayden-lee-696aba19a/
  github: https://github.com/jaydenhyunjinlee0811
